"""Adicionar campo requires_tracking no StockItem

Revision ID: 7cdda8dc9e36
Revises: a909d533700d
Create Date: 2025-09-05 08:10:01.650949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdda8dc9e36'
down_revision = 'a909d533700d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_tracking', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.drop_column('requires_tracking')

    # ### end Alembic commands ###
