"""empty message

Revision ID: 7dc0cf1dda79
Revises: b0f52d55ec40
Create Date: 2025-09-06 08:15:46.373566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc0cf1dda79'
down_revision = 'b0f52d55ec40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=False))
        # ADICIONE O PARÂMETRO 'constraint_name' NAS DUAS LINHAS ABAIXO
        batch_op.create_unique_constraint(batch_op.f('uq_user_cpf'), ['cpf'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # ADICIONE O PARÂMETRO 'constraint_name' NAS DUAS LINHAS ABAIXO
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_cpf'), type_='unique')
        batch_op.drop_column('cpf')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
