"""Add SchedulingLink model

Revision ID: b600ac14b51d
Revises: e9f358d9a9bb
Create Date: 2025-09-07 18:47:21.335789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b600ac14b51d'
down_revision = 'e9f358d9a9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduling_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_link_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_link_token'))

    op.drop_table('scheduling_link')
    # ### end Alembic commands ###
