"""Add category to stock items

Revision ID: f8429e158da1
Revises: 7dc0cf1dda79
Create Date: 2025-09-06 15:21:16.427380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8429e158da1'
down_revision = '7dc0cf1dda79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default='Geral'))
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
